# https://hub.docker.com/_/alpine
FROM alpine:3.13.5
LABEL MAINTAINER Kenji Yamada <kenji.yamada@gmail.com>

ARG UID=501
ARG GID=100
ARG GROUPNAME=users
ARG USERNAME=kyamada
ARG USERPASSWORD=password

RUN apk add bash sudo
RUN adduser -u ${UID} -G ${GROUPNAME} -h /home/${USERNAME} -s /bin/bash -D ${USERNAME} \
  && adduser ${USERNAME} wheel \
  && echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
  && echo ${USERNAME}:${USERPASSWORD} | chpasswd

USER ${USERNAME}
WORKDIR /home/${USERNAME}

CMD /bin/bash

